---
title: "Implémentation d'une méthode d'énumération de structure moléculaire à partir d'un arbre de fragmentation issu de spectrométrie de masse"
output: 
  pdf_document:
        template: report_template.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Matériels et méthodes : 

### Matériels
...

### Modélisation de la molécule et de son arbre de fragmentation



### Stratégie adoptée :

Rappel : l'objectif est d'énumérer toutes les configurations structurelles possible qu'une molécule puisse prendre tout en respectant un arbre de fragmentation.  
D'après [papier], il a été démontré qu'à partir de n'importe quel graphe respectant un arbre de fragmentation, il est possible de reconstruire le supergraphe composé de tous les graphes répondant à ces contraintes de séquence de degré grâce à une opération appelée le switch (ou le swap, plusieurs dénominations existent dans la littérature).  

Un point sur le switch :
[A redéfinir]
~Le switch est tout simplement l'opération consistant, étant deux arêtes d'un graphe, à en intervertir deux sommets, nous redonnant au final deux nouvelles arêtes.  
~Deux switches différents peuvent être appliqués sur un jeu de deux arêtes :    
[Schéma switch : straight/crossed]  
Cette opération a la propriété de ne pas modifier la séquence de degré du graphe dont sont issues les arêtes.  

En appliquant toutes les opérations de switch possible au sein d'un graphe (c-a-d, sur chaque paire d'arêtes), nous pouvons énumérer tous les graphes répondant aux contraintes de l'arbre de fragmentation : le supergraphe obtenu se compose en effet de chacun de ces graphes, reliés par l'opération de switch qui nous a permis de passer de l'un à l'autre.  
[Schéma du supergraphe]  
Plus précisément, ce supergraphe se compose de tous les graphes respectant les contraintes imposées par une séquence de degré : il contient également tous les graphes non-connexes. Cependant, d'après [Taylor], il a été démontré que le supergraphe ne perdait pas sa propriété de connexité lorsque sont retirés les sous-graphes non connexes. Ainsi, quelque soit le graphe (connexe) de départ du supergraphe, il existera toujours un chemin (correspondant à une suite de switches) le reliant à n'importe quel autre graphe connexe.  
 [schéma ?]  
 
 ! On peut passer d'un graphe qui répond à l'arbre de frag à tous les autres [ futur papier]
 
Cela nous permet d'affirmer qu'à partir d'un seul graphe valide, nous pouvons en déduire toutes les solutions existantes pour une séquence de degré.  

Il faudra ensuite faire un tri pour ne conserver que les graphes respectant également les conditions de connexité induites par chaque noeud de l'arbre de fragmentation (à savoir que chaque ensemble de sommet d'un noeud doit être connexe).  

### Algorithme de résolution

#### Génération du premier graphe respectant l'arbre de fragmentation :
Apparté :  
binomial(binomial(18,2), 38) pour graphe simple uniquement
binomial(18,2)^ 38 pour multi : supérieur nombre d'atome dans l'univers
Soit une molécule composée de n atomes.  
Soit sum(di) la somme de la séquence de degré correspondante.  
Le nombre d'arêtes du graphe représentant cette molécule est égal à sum(di)/2. -> nb_e_tot  
Le nombre d'arêtes minimum pour obtenir un graphe connexe est égal à (n-1). -> nb_e_min  
Combien peut-on construire de graphe connexe non-isomorphe avec seulement (n-1) arêtes?  
Le nombre d'arête a ajouter une fois avoir obtenu ce graphe connexe est de sum(di/2) - (n-1). -> nb_e_to_add  
  
Exemple : C2N3O2H3  
sum(di) = 24  
nb_e_tot = sum(di)/2 = 12  
nb_e_min = nb_atom -1 = 9  
nb_e_to_add = nb_e_tot - nb_e_min = 3  
?? D'après nauty (geng -c 9 10:10 -u), 797 graphes simples connexes et non-isomorphes existent pour nb_e_min = 9 arètes pour 10 sommets.   

##### Validité de l'arbre de fragmentation et de la séquence de degré
La procédure à suivre pour obtenir ce premier graphe doit être particulièrement rigoureuse si nous voulons qu'elle soit adaptée quelque soit la composition de la molécule et son arbre de fragmentation.  

Dans un premier temps, précisons qu'il est possible de vérifier au préalable qu'une solution existe réellement.  
Pour cela, ... respect des 3 conditions ...  
Si ces conditions sont respectées alors d'après [papier], il a été démontré qu'au moins une solution existe pour ce problème.  

Pour trouver ce premier graphe, il est ensuite nécessaire, après avoir généré un sommet par atome, d'ajouter le bon nombre d'arête de telle sorte que chaque sommet atteigne exactement le degré imposé par la séquence de degré déduite de la formule chimique.  

##### Connexion des feuilles
Un des premières difficultés pouvant être rencontrée lors de la génération du premier graphe concerne la gestion des sommets nécessitant un grand nombre de degré.  
En effet, si la distribution des arêtes entre les sommets n'est faite correctement, il est possible qu'un sommet se retrouve seul avec un nombre pair de liaison à distribuer : or, étant donné que les loops soient interdits, le graphe doit être considéré comme invalide.  
Pour avoir la certitude que cela n'arrive pas, une des solutions est de construire un arbre courant, pour chaque premier ensemble d'atome de l'arbre de fragmentation. Cela revient à ajouter le minimum d'arête possible pour connecter les sommets de chacunes des feuilles. L'objectif est ici de prévenir le problème que peuvent poser les sommets de fort degré tout en assurant la connexité des feuilles du graphe.  
Brève description de l'algo en schéma :  
[Liste des atomes connectés et non_connectés d'une feuille. Jusqu'à ce que tous les atomes soient connectés : on prend dans chacunes des listes l'atome à qui il reste le plus de liaison à établir et on ajoute une arête dans le graphe entre ces deux atomes]  

En itérant cette procédure sur toutes les feuilles, nous sommes ensuite en mesure d'établir récursivement des arêtes au niveau des noeuds supérieurs de l'arbre de fragmentation sans avoir à ajouter des boucles.  

##### Connexion des noeuds supérieurs
Une fois les premiers niveaux connectés (les feuilles), nous pouvons commencer à répondre aux contraintes de connexité imposées par l'arbre de fragmentation dans les noeuds supérieurs.  
Pour les mêmes raisons que précédemment, il est plus prudent de d'abord établir la bonne connexité des noeuds, avant de commencer à combler les sommets en ajoutant des liaisons.  
La démarche adoptée dans notre cas a été de partir des feuilles de l'arbre, puis de remonter récursivement les noeuds de l'arbre jusqu'à la racine, en ajoutant des arêtes de manière à connecter les noeuds de même parent (toujours au niveau des atomes des noeuds disposant du plus grand nombre de liaison à distribuer).  
[petit schéma]  
Cela revient à établir un arbre courant mimant la hiérarchie de l'arbre de fragmentation.  
Nous obtenons à la fin de cette étape un graphe simple, sans boucle, non-dirigé, respectant toutes les conditions de connexité entre atomes de l'arbre de fragmentation : la dernière condition à respecter pour obtenir un premier graphe valide est de combler les sommets disposant encore de degré à distribuer.  

##### Ajout des dernières arêtes
Grâce aux précautions prises lors des étapes précédentes, nous disposons d'un nombre pair de degré libre, et ceux-ci sont dispersés sur plusieurs sommets.  
En suivant le même protocole que précédemment, et en tenant compte cette fois de tous ces atomes quelque soit leur noeud, nous pouvons ajouter les dernières arêtes jusqu'à ne plus avoir de degré libre. Le graphe ainsi obtenu est un multigraphe, sans boucle.  
Nous obtenons ainsi un premier graphe respectant toutes les contraintes de l'arbre de fragmentation.  

### Génération de tous les graphes valides

D'après [papier], il est possible d'obtenir tous les graphes connectés respectant l'arbre de fragmentation à partir d'un seul graphe connecté.  
Cela revient à parcourir le supergraphe en partant du premier graphe en effectuant des opérations de switches successifs, 


### Optimisation

-isomorphisme
-optimisation hydrogene + verif connexité LCA

perspectives
algo :
- réduire switch candidats à ceux qui garde connexité
- diamètre du graphe
bio : 
-système de score
-fragments déjà connus plus pertinents (plus stringents)


Algo implémenté équivalent aux critères d'existence d'une solution

Contexte :
Métabolomics, MS/MS, identification de métabolite
Pourquoi métabo? car plus compliqué, 
focus sur les petits métabolites, pas dans BDD
Problématique : a partir d'une voie de frag, lister structures
Etat de l'art :
Expliquer à partir du cas de base : juste formule brute -> identification et construction par Senior 1951 : condition d'existence (preuve constructive) et Hakimi
Puis, énumération [taylor 81 à vérifier] trouver tous les multigraphes connexes qui vérifient séquence de degré.

Intro arbre de frag :
Pourquoi voie de fragmentation : élimination de plein de candidats
Plus précis.
Ambiguité arbre de frag/voie de frag : si plusieurs voies : plus de précision car on recoupe les candidats des voies.
On part du principe qu'on part d'un arbre qui est une voie de fragmentation généralisée (plus de 2 fragments possibles)
Etape préalable de reconstruction de l'arbre de fragmentation valide (besoin de connaissance en biochimie pour gérer réarrangements)
Pas évident de prendre en compte cas réel car besoin de traitement à la main -> pipeline pas encore complet



### Introduction
[On présente un peu tout, mais pas de manière formelle.]

### Préliminaires

Définition:
Switch
Arbre de fragmentation
Voie de fragmentation (celle qui ne consiste pas juste en un arbre binaire)
Degré
Multigraphes
loop-free
Connexité
Séquence de degré
MS/MS

L'identification d'une molécule et l'élucidation de sa structure sont des informations essentielles et prisées dans de nombreux domaines scientifiques.
Plus récemment, le développement de nouvelles technologies a grandement amélioré les méthodes d'analyse moléculaire. C'est notamment le cas de la spectrométrie de masse en tandem, qui s'est rapidement positionnée comme le nouveau gold standard dans ce domaine. 
Si cette technologie est efficace dans l'identification d'une grande majorité de molécule (les protéines par exemple), elle atteint toutefois certaines limites lorsque la molécule en question   le cadre de la protéomique
La métabolomique consiste en l'étude des métabolites, petits composés organiques produits du métabolisme.
La spectrométrie de masse est une technique physique permettant l'analyse de composé chimique. Très brièvement, cette technique consiste en une mesure du rapport M/Z (masse/charge) après ionisation de la molécule. Le spectre de masse ainsi obtenu nous permet d'assimiler des masses aux fragments de la molécule analysée et d'en déduire sa composition.

La spectrométrie de masse en tandem (aussi appelée MS/MS ou MS²), est une technique consistant en l'enchainement de plusieurs étapes de  MS, entrecoupées à chaque étape d'une opération de fragmentation. Les ions voués à être refragmentés (appelés ions précurseurs) sont choisis d'après leur rapport masse/charge après la première spectrométrie de masse (MS1), et les ions résultants de cette refragmentation sont eux-mêmes séparés et détectés par une deuxième spectrométrie de masse (MS2).
Cela nous permet d'obtenir une plus grande précision quant à l'identification d'une molécule et sa structure.
Nous pouvons ainsi suivre le devenir d'une molécule et de ses produits tout au long de ses fragmentations successives.
Toutes ces informations de fragmentation sont récupérées au fur à mesure et représentées de manière hiérarchique dans ce que l'on appelle une voie de fragmentation.
Etant donné qu'une molécule peut se briser de bien des manières, il existe en réalité pour une molécule plusieurs voies de fragmentation : un moyen de représenter toutes ces voies de fragmentation ensemble est de les rassembler dans un arbre de fragmentation, où la molécule totale est assimilée à la racine, et où tous les branches issues de la racine consiste en une nouvelle voie de fragmentation.
[schéma arbre de fragmentation]
[Attention, nous on utilise le terme d'arbre de fragmentation de manière différente : une voie, pas binaire]

Soit la formule chimique associée à une molécule. D'après un arbre de fragmentation, nous pouvons associer à chaque noeud un fragment de la molécule. Ce noeud représente un ensemble d'atome dont la connexité a été conservée après fragmentation : nous faisons pour l'instant le choix de ne pas prendre en compte les potentiels réarrangements. [Note : c'est une hypothèse évidemment trop simpliste, nous reviendrons dessus plus tard -> analyse préalable au cas par cas]  
D'après les propriétés de valence des atomes, il est ainsi possible de modéliser un atome comme étant un sommet du graphe, nécessitant d'être connecté par un nombre précis d'arêtes correspondant à sa valence. Le degré de chaque sommet du graphe devra correspondre exactement à la valence de l'atome auquel il est associé.  
  
[Insérer graphe exemple]  
  
Par extension, à une formule chimique correspond une séquence de degré.  


[Insérer graphe exemple]  
  
Chaque noeud de l'arbre de fragmentation apporte ainsi des contraintes de connexité supplémentaires à tous les atomes qui le compose.
Nous pouvons nous représenter cet arbre de fragmentation comme un supergraphe, connecté, composé de graphes connectés correspondant aux noeuds enfant de la racine de l'arbre, eux-même composés de sous-graphes connexes associés aux petits-enfants de la racine; et cela jusqu'à ce que l'on atteigne les feuilles de l'arbre.  
  
[Big schéma d'une patate-matriochka] -> définir feuille, noeud, racine  
feuille = premier ensemble de sommet  
  
Modéliser d'une telle manière l'arbre de fragmentation permet de poser le problème visuellement et de déduire les règles de connexion que devront respecter chaque noeud de l'arbre.  






 


