
# This file was *autogenerated* from the file graphs.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4)
class Vertex:
    def __init__(self):
        self.degree = _sage_const_0 
        self.index = None
        self.freeBonds = _sage_const_0 

    def __lt__(self, other):
        return self.freeBonds < other.free_bonds

    def __repr__(self):
        return str(self.index)

class Node:
    def __init__(self):
        self.vertices = []
        self.parent = None
        self.children = []
        self.minimumGraphs = []

def set_vertex(index, degree):
    vertex = Vertex()
    vertex.degree = degree
    vertex.index = index
    vertex.freeBonds = degree
    return vertex

def set_node(index, vertices_list):
    node = Node()
    node.index = index
    node.vertices = vertices_list
    return node

C1 = set_vertex("C1", _sage_const_4 )
H1 = set_vertex("H1", _sage_const_1 )

N01 = set_node("CH", [C1,H1])
print(C1)






