
# This file was *autogenerated* from the file spectro2.sage
from sage.all_cmdline import *   # import sage library

def TODO():
    raise NotImplementedError("To be implemented")


class Fragmentation_Tree:
    def __init__(self):
        self.root = None
        self.leaves = []

    def find_all_conformations(self):
        TODO()

t = Fragmentation_Tree()
t.find_all_conformations()






